title: Kosmi Blog  
email: kosmi@kosmi.io
description: >- # this means to ignore newlines until "baseurl:"
  Discover the latest updates, tips, and tricks for using Kosmi, the ultimate virtual hangout space. Stay connected with friends through video chat, games, and watch parties. Explore our blog for insights, tutorials, and community stories to enhance your Kosmi experience.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kosmihq
github_username:  kosmigramma

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
